name: example
version: 0.0.5
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_json.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: '^1.0.0'
  built_json: '^0.0.5'
  built_value: '^0.0.6'
  enum_class: '^0.0.6'

dev_dependencies:
  built_json_generator: '^0.0.5'
  built_value_generator: '^0.0.6'
  enum_class_generator: '^0.0.6'
  test: any
