name: chat_example
version: 0.1.2
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_json.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: '^1.0.0'
  built_json: '^0.1.4'
  built_value: '^0.1.3'
  enum_class: '^1.0.0'
  package_resolver: ^1.0.0 
  route: '>=0.4.6'

dev_dependencies:
  built_json_generator: '^0.1.4'
  built_value_generator: '^0.1.3'
  enum_class_generator: '^1.0.0'
  test: any
